import os
import re
import subprocess
from typing import Dict, List, Optional
import yt_dlp

ASSETS_FOLEY_DIR = os.path.abspath("data/assets/foley")
ASSETS_MUSIC_DIR = os.path.abspath("data/assets/music")

# Built-in sound aliases for fuzzy matching
SOUND_ALIASES = {
    "knife": "knife_chop.mp3",
    "chop": "knife_chop.mp3",
    "slice": "knife_chop.mp3",
    "cutting": "knife_chop.mp3",
    "sizzle": "sizzle.mp3",
    "fry": "sizzle.mp3",
    "boil": "sizzle.mp3",
    "crunch": "crunch.mp3",
    "bite": "crunch.mp3",
    "chew": "crunch.mp3",
    "eat": "crunch.mp3",
    "meow": "meow.mp3",
    "cat": "meow.mp3",
    "kitten": "meow.mp3",
    "purr": "meow.mp3",
    "ding": "ding.mp3",
    "bell": "ding.mp3",
    "chime": "ding.mp3",
    "whoosh": "whoosh.mp3",
    "swoosh": "whoosh.mp3",
    "swing": "whoosh.mp3",
    "punch": "whoosh.mp3",
    "bonk": "bonk.mp3",
    "thud": "bonk.mp3",
    "hit": "bonk.mp3",
    "slap": "bonk.mp3",
    "quack": "quack.mp3",
    "duck": "quack.mp3",
    "bark": "bark.mp3",
    "dog": "bark.mp3",
    "puppy": "bark.mp3",
    "woof": "bark.mp3",
    "boing": "boing.mp3",
    "spring": "boing.mp3",
    "bounce": "boing.mp3",
    "jump": "boing.mp3",
}

def resolve_foley_sound(action_type: str) -> str:
    """
    Finds matching sound file in local assets bank or auto-fetches
    clean royalty-free SFX via yt-dlp if novel sound is requested.
    """
    os.makedirs(ASSETS_FOLEY_DIR, exist_ok=True)
    clean_key = re.sub(r'[^a-zA-Z0-9]', '', action_type.lower())

    # 1. Exact or alias match
    for k, filename in SOUND_ALIASES.items():
        if k in clean_key or clean_key in k:
            fpath = os.path.join(ASSETS_FOLEY_DIR, filename)
            if os.path.exists(fpath):
                return fpath

    # 2. Check if file with this name exists in foley dir
    direct_path = os.path.join(ASSETS_FOLEY_DIR, f"{clean_key}.mp3")
    if os.path.exists(direct_path):
        return direct_path

    # 3. Dynamic Auto-Fetch: download clean sound effect from YouTube
    print(f"[AUDIO DIRECTOR] Novel sound effect requested: '{action_type}'. Auto-fetching into sound bank...")
    out_tmpl = os.path.join(ASSETS_FOLEY_DIR, f"{clean_key}.%(ext)s")
    search_q = f"ytsearch1:{action_type} sound effect clean short"
    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': out_tmpl,
        'quiet': True,
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }]
    }
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([search_q])
        if os.path.exists(direct_path):
            print(f"[AUDIO DIRECTOR] Successfully cached new SFX: {clean_key}.mp3")
            return direct_path
    except Exception as e:
        print(f"[AUDIO DIRECTOR] Auto-fetch error: {e}. Falling back to default bonk.")

    # Fallback to bonk or ding
    fallback = os.path.join(ASSETS_FOLEY_DIR, "bonk.mp3")
    if not os.path.exists(fallback):
        fallback = os.path.join(ASSETS_FOLEY_DIR, "ding.mp3")
    return fallback

def resolve_music_track(vibe: str) -> str:
    """
    Finds or defaults background comedy / cartoon music track.
    """
    os.makedirs(ASSETS_MUSIC_DIR, exist_ok=True)
    default_music = os.path.join(ASSETS_MUSIC_DIR, "bouncy_comedy.mp3")
    if not os.path.exists(default_music):
        temp_music = "data/temp/cartoon_music.mp3"
        if os.path.exists(temp_music):
            return os.path.abspath(temp_music)
    return default_music

def build_scene_audio_timeline(story: Dict, total_duration: float = 8.6, output_wav: str = "data/temp/master_studio_audio.wav") -> str:
    """
    Dynamically analyzes ANY story generated by the AI:
    - Identifies each scene's timing and required Foley action.
    - Resolves high-fidelity audio assets.
    - Assembles precise millisecond delay offsets in FFmpeg filter_complex.
    - Ducks background music under the Foley punches.
    """
    scenes = story.get("scenes", [])
    music_vibe = story.get("music_vibe", "bouncy_comedy")
    bgm_path = resolve_music_track(music_vibe)

    inputs = ["-i", bgm_path]
    filter_parts = []
    mix_inputs = ["[bgm]"]

    # Background music ducked bed
    filter_parts.append(f"[0:a]volume=0.20,atrim=0:{total_duration},asetpts=PTS-STARTPTS[bgm]")

    # Scene timing partitions:
    # Scene 1: 0.0s -> 2.8s
    # Scene 2: 2.8s -> 5.6s
    # Scene 3: 5.6s -> 8.6s
    scene_offsets = [0.3, 3.2, 6.0]

    input_idx = 1
    for i, sc in enumerate(scenes[:3]):
        sound_type = sc.get("foley_sound_type", "bonk")
        sfx_path = resolve_foley_sound(sound_type)
        inputs.extend(["-i", sfx_path])

        delay_ms = int(scene_offsets[i] * 1000)
        dur = 2.4 if i < 2 else 2.6
        label = f"sfx{i+1}"
        filter_parts.append(
            f"[{input_idx}:a]volume=1.8,atrim=0:{dur},asetpts=PTS-STARTPTS,adelay={delay_ms}|{delay_ms}[{label}]"
        )
        mix_inputs.append(f"[{label}]")
        input_idx += 1

        # If scene 3 has an ending punchline/ding, add finishing flourish
        if i == 2:
            ding_path = resolve_foley_sound("ding")
            inputs.extend(["-i", ding_path])
            ding_delay = int((total_duration - 1.0) * 1000)
            filter_parts.append(
                f"[{input_idx}:a]volume=1.3,atrim=0:1.5,asetpts=PTS-STARTPTS,adelay={ding_delay}|{ding_delay}[ding_finish]"
            )
            mix_inputs.append("[ding_finish]")
            input_idx += 1

    # Final amix
    amix_str = "".join(mix_inputs) + f"amix=inputs={len(mix_inputs)}:duration=first:dropout_transition=0,volume=1.2[aout]"
    filter_parts.append(amix_str)

    full_filter = ";".join(filter_parts)

    os.makedirs(os.path.dirname(output_wav), exist_ok=True)
    cmd = [
        "ffmpeg", "-y",
        *inputs,
        "-filter_complex", full_filter,
        "-map", "[aout]",
        "-c:a", "pcm_s16le",
        "-t", str(total_duration),
        output_wav
    ]

    print(f"[AUDIO DIRECTOR] Mixing dynamic Foley audio track for story: '{story.get('title')}'...")
    subprocess.run(cmd, check=True)
    print(f"[AUDIO DIRECTOR] Dynamic Foley audio rendered successfully: {output_wav}")
    return output_wav
